# Basic
title: 喵星人聚居地
subtitle: By ModerRAS
welcome_message: 
description: Just for fun!
creator: <a href="https://miaostay.com">@ModerRAS</a>

url: "https://miaostay.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
# cover_color: purple

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Games, description: Flash Games, url: 'https://flash.miaostay.com'}
    - {title: Friends, description: My Friends, url: 'https://miaostay.com/pages/friends.html'}


# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: moderras
    gitalk: moderras
    # duoshuo:
    # gitment: moderras

# Social
social:
    # weibo: onevcat
    github: ModerRAS
    twitter: ModerRAS
    gplus: 115238273383813111670
    mail: adqewsx@gmail.com

# Google Analytics
ga:
    id: UA-109836282-1
    host: miaostay.com
friends:
    - {url: 'https://rumia.club', avatar: 'https://avatars3.githubusercontent.com/u/37037548?s=400&v=4', name: Rumia, desc: "An overfit neural network"}

plugins:
  - jekyll-sitemap